version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: K90Y2ZiduWcrHCKGkzopAebrfsDAPUCbS1kEAAhj0b00BayqYaidxg1KdgLIeRV
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDITCCAgmgAwIBAgIJLAPvpsvGpqQwMA0GCSqGSIb3DQEBCwUAMC4xLDAqBgNV\nBAMTI2NvbW11bml0eS1leHBlbnNlcy1kZXYuZXUuYXV0aDAuY29tMB4XDTE5MTIw\nNTIxNDg1OFoXDTMzMDgxMzIxNDg1OFowLjEsMCoGA1UEAxMjY29tbXVuaXR5LWV4\ncGVuc2VzLWRldi5ldS5hdXRoMC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw\nggEKAoIBAQDGXrEICcLyeaHG6APN23wtz85o0aJQ6fyAkUFMr2XA7WapCSquCMMp\nOXf509evAVqQyHivyfRYxors5vGsxn4ojy0sQbE9On+AlRdoWo9or6BBL881PLek\njn2zWzMV135VoBq81mth1n8ENWOIlpTtRjmxqaUsMgKBeaZ2XmsBfTGXV+sOocxP\nhqaP6JGjwVmU1NCRI8I/Nwd4YR20vczk/3+YQMx/awsmGOhHQpjGOtI7Q4j2CnWM\nrZbEhAuVazurluwmLnVYp55cxl5yACewy4wdDOxgS3PB+YRayTA5NqIzwARrmRQw\nkPPgryGVnCWthP6J4T6sKfDnv0OlGs2ZAgMBAAGjQjBAMA8GA1UdEwEB/wQFMAMB\nAf8wHQYDVR0OBBYEFKHWApgg0xxfRdfs/DZzzHoU/nv8MA4GA1UdDwEB/wQEAwIC\nhDANBgkqhkiG9w0BAQsFAAOCAQEAok/qDj1AkVDej2rdXKGeEVNXUu7ZV0RGFS1W\ntFdUtrxwQMrF+Nz+I+MSQ/UQCXTNexHLqQPUuzNdF69pHtkNoBSZXMyaG6ILqPGj\n4+2delxatvFVHvs9xaMdfMQkyPQtPbz2gFb2wHB+X/CgLU9+TJOT29PdDLxqKaHn\nPqror3thTLvIr4CgEQ0/wWaYi8/Y02D3GBLT7vYvPfbBXHYsVMMqslGtHOZwweMR\n16QknKpgt9Fl7/ZsodJ+kJ0lgUlgvCIceTXOn/pjAqHKd9yfwVWOTftEcXCsUxwl\nMBgQSr6dPkR9ehFKxi/TuzdS8MGBfHZUBcJbpjFDz2YXk204LA==\n-----END CERTIFICATE-----\n"}'
volumes:
  db_data:
